apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-orders
spec:
  replicas: 2
  selector:
    matchLabels:
      app: svc-orders
  template:
    metadata:
      labels:
        app: svc-orders
    spec:
      containers:
        - name: svc-orders
          image: ghcr.io/ORG/svc-orders:TAG
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet: { path: /health, port: 8000 }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /health, port: 8000 }
            initialDelaySeconds: 10
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: svc-orders
spec:
  selector:
    app: svc-orders
  ports:
    - port: 80
      targetPort: 8000
  type: ClusterIP
